name: Daily Medical AI News Update

on:
  schedule:
    - cron: '0 23 * * *'  # UTC 23:00 = London 7:00 AM (UTC+8)
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests google-api-python-client
        
    - name: Fetch medical AI news
      run: python fetch_news.py
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }}
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add news.json
        git diff --staged --quiet || git commit -m "Update daily medical AI news"
        git push